{{- if .Values.persistence.state.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "metube.fullname" . }}-state
  labels:
    {{- include "metube.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.state.accessMode | quote }}
  {{- if .Values.persistence.state.storageClass }}
  storageClassName: {{ .Values.persistence.state.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.state.size }}
{{- end }} 