apiVersion: v1
kind: Service
metadata:
  name: {{ include "metube.fullname" . }}
  labels:
    {{- include "metube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.reverseProxy.enabled }}
      targetPort: nginx
      {{- else }}
      targetPort: http
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "metube.selectorLabels" . | nindent 4 }}
