---
apiVersion: v2
version: "1.0.13"
appVersion: 1.123.0
name: matrix-synapse
description: Matrix reference homeserver
icon: https://matrix.org/images/matrix-logo.svg
type: application
maintainers:
  - name: ebadfd
    url: https://ebadfd.tech
keywords:
  - matrix
  - synapse
dependencies:
  - name: postgresql
    version: "^16.3.1"
    repository: "oci://docker.io/bitnamicharts"
    condition: postgresql.enabled
  - name: redis
    version: "20.7.0"
    repository: "oci://docker.io/bitnamicharts"
    condition: redis.enabled
